project:
  type: website

website:
  title: "CSHLData2023"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - schedule.qmd
      - references.qmd
    right:
      - icon: github
        href: https://github.com/seandavi/CSHLData2023
        aria-label: GitHub


format:
  html:
    theme: 
      light: [cosmo, styles.scss]
      dark: cyborg
    toc: true



